version: "3.6"
services:
  spark-master:
    image: jpazzini/mapd-b:spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - $PWD:/opt/workspace
  spark-worker:
    image: jpazzini/mapd-b:spark-worker
    depends_on:
      - spark-master
    volumes:
      - $PWD:/opt/workspace
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
  zookeeper:
    image: jpazzini/mapd-b:zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka-broker:
    image: jpazzini/mapd-b:kafka-broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
  jupyterlab:
    image: jpazzini/mapd-b:spark-jupyter
    container_name: jupyterlab
    depends_on:
      - spark-master
    ports:
      - 4040:4040
      - 8888:8888
    volumes:
      - $PWD:/opt/workspace
